#!/bin/bash
#SBATCH --job-name paraAIM
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --time=0-00:10:00
#SBATCH --partition=thin
#SBATCH --mem=6000

# Change to the directory where the files are located
cd $SLURM_SUBMIT_DIR

# You may need to change the module name
module load 2021
module load Anaconda3/2021.05

# It is assumed that the bin files are already in your home
# You may have to change the location of the programme
python EparAIM.py Parameter.txt 32

